<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Dmytros-MBP" failures="1" tests="1" name="com.united.TestRunner" time="15.856" errors="0" timestamp="2021-12-14T09:36:03 EST" skipped="0">
  <testcase classname="com.united.TestRunner" name="runScenario" time="15.856">
    <failure message="expected [4] but found [0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [4] but found [0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.united.steps.Smoke_Tests.page_is_loaded_verify_following_tabs_are_present(Smoke_Tests.java:14)
at âœ½.page is loaded verify following tabs are present(file:///Users/dkaplunskyi/IdeaProjects/united/src/test/resources/features/Smoke_Tests.feature:5)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.united.TestRunner -->
